### ISSUE TITLE
Instructions of using StreamBWA

### ISSUE THREAD

**Issue by Maryom** [HamidMushtaq/StreamBWA#1]
Hi,

Thanks for your repo.

Could you please update the readme with the instructions of using StreamBWA ? I would like to compare my implementation with StreamBWA and I will cite it.

Best regards,
Mariam

**Comment by HamidMushtaq** [comment]
Hi Maryom,

Sorry for not reading your message before. I will try to put the instructions as soon as possible.

Regards,
Hamid.

**Comment by Maryom** [comment]
Thanks for your reply. Please do it ASAP because I need to use it in my research and I will cite your work inshallah.

**Comment by HamidMushtaq** [comment]
Hi Maryom,

I've now added the instructions.

Regards,
Hamid.

**Comment by Maryom** [comment]
Thank you. Inshallah I will compare it with my work ASAP.
